// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: s7EEJcVdeDttPbcVMFDKQR

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { AntdConfigProvider } from "@plasmicpkgs/antd5/skinny/registerConfigProvider";
import { Web3GlobalContext } from "suinova-nft-builder/dist/index.js";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  antdConfigProviderProps?: Partial<
    Omit<React.ComponentProps<typeof AntdConfigProvider>, "children">
  >;

  web3GlobalContextProps?: Partial<
    Omit<React.ComponentProps<typeof Web3GlobalContext>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, antdConfigProviderProps, web3GlobalContextProps } = props;

  return (
    <AntdConfigProvider
      {...antdConfigProviderProps}
      borderRadius={
        antdConfigProviderProps && "borderRadius" in antdConfigProviderProps
          ? antdConfigProviderProps.borderRadius!
          : 6
      }
      colorBgBase={
        antdConfigProviderProps && "colorBgBase" in antdConfigProviderProps
          ? antdConfigProviderProps.colorBgBase!
          : "#ffffff"
      }
      colorError={
        antdConfigProviderProps && "colorError" in antdConfigProviderProps
          ? antdConfigProviderProps.colorError!
          : "#ff4d4f"
      }
      colorInfo={
        antdConfigProviderProps && "colorInfo" in antdConfigProviderProps
          ? antdConfigProviderProps.colorInfo!
          : "#1677ff"
      }
      colorPrimary={
        antdConfigProviderProps && "colorPrimary" in antdConfigProviderProps
          ? antdConfigProviderProps.colorPrimary!
          : "#1677ff"
      }
      colorSuccess={
        antdConfigProviderProps && "colorSuccess" in antdConfigProviderProps
          ? antdConfigProviderProps.colorSuccess!
          : "#52c41a"
      }
      colorWarning={
        antdConfigProviderProps && "colorWarning" in antdConfigProviderProps
          ? antdConfigProviderProps.colorWarning!
          : "#faad14"
      }
      controlHeight={
        antdConfigProviderProps && "controlHeight" in antdConfigProviderProps
          ? antdConfigProviderProps.controlHeight!
          : 32
      }
      defaultDark={
        antdConfigProviderProps && "defaultDark" in antdConfigProviderProps
          ? antdConfigProviderProps.defaultDark!
          : false
      }
      lineWidth={
        antdConfigProviderProps && "lineWidth" in antdConfigProviderProps
          ? antdConfigProviderProps.lineWidth!
          : 1
      }
      loadingText={
        antdConfigProviderProps && "loadingText" in antdConfigProviderProps
          ? antdConfigProviderProps.loadingText!
          : undefined
      }
      removeLoading={
        antdConfigProviderProps && "removeLoading" in antdConfigProviderProps
          ? antdConfigProviderProps.removeLoading!
          : undefined
      }
      sizeStep={
        antdConfigProviderProps && "sizeStep" in antdConfigProviderProps
          ? antdConfigProviderProps.sizeStep!
          : 4
      }
      sizeUnit={
        antdConfigProviderProps && "sizeUnit" in antdConfigProviderProps
          ? antdConfigProviderProps.sizeUnit!
          : 4
      }
      themeStyles={
        antdConfigProviderProps && "themeStyles" in antdConfigProviderProps
          ? antdConfigProviderProps.themeStyles!
          : true
          ? {
              fontFamily: "Roboto",
              fontSize: "16px",
              fontWeight: "400",
              lineHeight: "1.5",
              color: "#535353",
              letterSpacing: "normal"
            }
          : undefined
      }
      wireframe={
        antdConfigProviderProps && "wireframe" in antdConfigProviderProps
          ? antdConfigProviderProps.wireframe!
          : false
      }
    >
      <Web3GlobalContext
        {...web3GlobalContextProps}
        contractPackageId={
          web3GlobalContextProps &&
          "contractPackageId" in web3GlobalContextProps
            ? web3GlobalContextProps.contractPackageId!
            : "0x2d99da054514ff31c7e7da82751d11bb16b53c66290c435a409e17c8992e35ed"
        }
        createdCollection={
          web3GlobalContextProps &&
          "createdCollection" in web3GlobalContextProps
            ? web3GlobalContextProps.createdCollection!
            : "ec9e0557-a72e-4b2c-9d30-99b36ec01e99"
        }
        importedCollection={
          web3GlobalContextProps &&
          "importedCollection" in web3GlobalContextProps
            ? web3GlobalContextProps.importedCollection!
            : "0x847d5967dccc496ef9f5dc3673f1e7d174743fbd9d9e29e8c54c33eb74d912d5"
        }
        mintingInfo={
          web3GlobalContextProps && "mintingInfo" in web3GlobalContextProps
            ? web3GlobalContextProps.mintingInfo!
            : {
                id: "ec9e0557-a72e-4b2c-9d30-99b36ec01e99",
                projectId: "s7EEJcVdeDttPbcVMFDKQR",
                collectionId:
                  "0x44a52f1188387c8ce0268fc85bcddd8deae5f723ac80e7ecf9c5f5f086a5f611",
                admin:
                  "0x7c484896d088f2eb3012cac48de62fd4ec02c54540cbb1cd5e312e02216d055a",
                name: "demo project 1",
                description:
                  "demo project 1demo project 1demo project 1demo project 1demo project 1demo project 1demo project 1demo project 1demo project 1demo project 1demo project 1demo project 1demo project 1demo project 1",
                imageUrl:
                  "https://s3-development-25.s3.ap-southeast-1.amazonaws.com/15278e7b836bbd7c83e48abbb095c56a.png",
                royaltyFee: "0",
                hasPresale: false,
                whitelistStartTime: "1749352720",
                whitelistEndTime: "0",
                presaleStartTime: "1749352720",
                presaleEndTime: "0",
                presaleNftPrice: "0",
                presaleWhitelistedUsers: [],
                presaleTotalNft: "0",
                presaleNftPerUser: "0",
                publicSaleStartTime: "1749352720",
                publicSaleEndTime: "0",
                publicNftPrice: "0",
                nftPerUser: "0",
                totalSupply: "0",
                mintedSupply: "0",
                status: "ACTIVE",
                createdAt: "2025-06-07T19:18:40.340Z",
                updatedAt: "2025-06-07T19:18:46.843Z",
                items: [
                  {
                    id: "71",
                    launchpadId: "ec9e0557-a72e-4b2c-9d30-99b36ec01e99",
                    name: "background",
                    description:
                      "backgroundbackgroundbackgroundbackgroundbackgroundbackgroundbackgroundbackgroundbackgroundbackgroundbackgroundbackgroundbackgroundbackgroundbackgroundbackgroundbackgroundbackgroundbackgroundbackground",
                    imageUrl:
                      "https://s3-development-25.s3.ap-southeast-1.amazonaws.com/15278e7b836bbd7c83e48abbb095c56a.png",
                    attributes: [
                      { value: "red", trait_type: "background" },
                      { value: "gray", trait_type: "background" }
                    ],

                    creator:
                      "0x7c484896d088f2eb3012cac48de62fd4ec02c54540cbb1cd5e312e02216d055a",
                    createdAt: "2025-06-07T19:18:40.357Z",
                    updatedAt: "2025-06-07T19:18:40.357Z"
                  }
                ],

                visions: [
                  {
                    id: "48",
                    launchpadId: "ec9e0557-a72e-4b2c-9d30-99b36ec01e99",
                    description: "milestone1",
                    visionTime: "2025-06-08T03:17:19.839Z",
                    createdAt: "2025-06-07T19:18:40.363Z",
                    updatedAt: "2025-06-07T19:18:40.363Z"
                  },
                  {
                    id: "49",
                    launchpadId: "ec9e0557-a72e-4b2c-9d30-99b36ec01e99",
                    description: "milestone2",
                    visionTime: "2025-06-09T03:17:20.000Z",
                    createdAt: "2025-06-07T19:18:40.363Z",
                    updatedAt: "2025-06-07T19:18:40.363Z"
                  },
                  {
                    id: "50",
                    launchpadId: "ec9e0557-a72e-4b2c-9d30-99b36ec01e99",
                    description: "milestone3",
                    visionTime: "2025-06-10T03:17:20.000Z",
                    createdAt: "2025-06-07T19:18:40.363Z",
                    updatedAt: "2025-06-07T19:18:40.363Z"
                  }
                ],

                teams: [
                  {
                    id: "45",
                    launchpadId: "ec9e0557-a72e-4b2c-9d30-99b36ec01e99",
                    memberName: "Member1",
                    memberTitle: "dev",
                    createdAt: "2025-06-07T19:18:40.371Z",
                    updatedAt: "2025-06-07T19:18:40.371Z"
                  },
                  {
                    id: "46",
                    launchpadId: "ec9e0557-a72e-4b2c-9d30-99b36ec01e99",
                    memberName: "Member2",
                    memberTitle: "dev",
                    createdAt: "2025-06-07T19:18:40.371Z",
                    updatedAt: "2025-06-07T19:18:40.371Z"
                  },
                  {
                    id: "47",
                    launchpadId: "ec9e0557-a72e-4b2c-9d30-99b36ec01e99",
                    memberName: "Member3",
                    memberTitle: "dev",
                    createdAt: "2025-06-07T19:18:40.371Z",
                    updatedAt: "2025-06-07T19:18:40.371Z"
                  }
                ]
              }
        }
      >
        {children}
      </Web3GlobalContext>
    </AntdConfigProvider>
  );
}
