// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: s7EEJcVdeDttPbcVMFDKQR
// Component: kenx_DaJRVMR

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { ConnectWalletButton } from "suinova-nft-builder/dist/index.js";
import { WalletIcon } from "suinova-nft-builder/dist/index.js";
import { CopyIcon } from "suinova-nft-builder/dist/index.js";
import { UserIcon } from "suinova-nft-builder/dist/index.js";
import { LogoutIcon } from "suinova-nft-builder/dist/index.js";
import { AntdAvatar } from "@plasmicpkgs/antd5/skinny/registerAvatar";
import { AntdTabs } from "@plasmicpkgs/antd5/skinny/registerTabs";
import { AntdTabItem } from "@plasmicpkgs/antd5/skinny/registerTabs";
import { AntdSteps } from "@plasmicpkgs/antd5/skinny/registerSteps";

import { useScreenVariants as useScreenVariantsiaU9BnxD99 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: IaU9-_BnxD99/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: 66MC2d9B7YecVEphuUMtqF/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: s7EEJcVdeDttPbcVMFDKQR/projectcss
import sty from "./PlasmicConnectWalletViewMintingNftDetails.module.css"; // plasmic-import: kenx_DaJRVMR/css

import HomeSvgIcon from "./icons/PlasmicIcon__HomeSvg"; // plasmic-import: 0svw8Rf6WBry/icon

createPlasmicElementProxy;

export type PlasmicConnectWalletViewMintingNftDetails__VariantMembers = {};
export type PlasmicConnectWalletViewMintingNftDetails__VariantsArgs = {};
type VariantPropType =
  keyof PlasmicConnectWalletViewMintingNftDetails__VariantsArgs;
export const PlasmicConnectWalletViewMintingNftDetails__VariantProps =
  new Array<VariantPropType>();

export type PlasmicConnectWalletViewMintingNftDetails__ArgsType = {};
type ArgPropType = keyof PlasmicConnectWalletViewMintingNftDetails__ArgsType;
export const PlasmicConnectWalletViewMintingNftDetails__ArgProps =
  new Array<ArgPropType>();

export type PlasmicConnectWalletViewMintingNftDetails__OverridesType = {
  root?: Flex__<"div">;
  svg?: Flex__<"svg">;
  walletIcon?: Flex__<typeof WalletIcon>;
  sub?: Flex__<"sub">;
  button?: Flex__<"button">;
  tabs?: Flex__<typeof AntdTabs>;
  steps2?: Flex__<typeof AntdSteps>;
};

export interface DefaultConnectWalletViewMintingNftDetailsProps {
  className?: string;
}

const $$ = {};

function PlasmicConnectWalletViewMintingNftDetails__RenderFunc(props: {
  variants: PlasmicConnectWalletViewMintingNftDetails__VariantsArgs;
  args: PlasmicConnectWalletViewMintingNftDetails__ArgsType;
  overrides: PlasmicConnectWalletViewMintingNftDetails__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "teamMembers",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [
          {
            name: "james",
            role: "Co Founder",
            image:
              "https://s3-alpha-sig.figma.com/img/21c1/c284/eddacccb4e22ee7d2abea1058a784bf2?Expires=1745193600&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=gCneODEcNL1rKq3gWwUkRGlMlkJiFOW-TSt3US569UZ3P2lun0RdhKinihk9KoYX7OFOXMaHGpH-NcFt6CbRZJRdIju7Ac9teLYODgx3M8j5PlwFRW9gpvvQJ88y5BZCW-tc7Ud0mJrcutMb7CVHtyRek9FVM2acomJeFji2h6wYaGQ5hC8-mWxMJRyEG1sxoJjUe8N0G3nDXDbvBlLi4GX0cpx-Ie1jxIt7jfnKoelViCqvdazv04PhghHCqOEDeXG68XlxoY45nY2aKZd~qyT5zAP98AgT-nxYMzIVtORNaH3UxVFAF32Bc~fpcRk8FkheFehe9hSyBV8rEBPysg__"
          },
          {
            name: "Bryan",
            role: "Co Founder",
            image:
              "https://s3-alpha-sig.figma.com/img/51a2/6677/88ebcdbeeab9f107b69a80d1053e1aa1?Expires=1745193600&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=nZgDTj9r9EJOqwOdteIogFbRnfPps9qzj63642UCBB7OyEexD585cAqh-R7ZkyRkxqKCoDJx2BYh3-rqougZe0FjFWtWXPbEV7usjJXGox1YbvoXlMBWXbb4RMk6lWnQux1VDxgrAIXvkr7Uuw4Rbee1wwGlkel89eLNOmePafMPIf5waCKHAlBDygchtYFFAk57ICg~o~leq-97YNz2tUsOgYoAESlD7fIOiVFoPzrJEbkG9KRYt~4laQ88xSRnWCU7bSnAxu468Riptg35Zs-kY1XNC671eFhD01ilEvzWi1-rmt2Biwcn7iiJlISyLfsgyDpAf~F~Av3c8d07bw__"
          },
          {
            name: "Emily",
            role: "Artist",
            image:
              "https://s3-alpha-sig.figma.com/img/b551/caf1/a50da17c794f41c2b771e5502c81c73e?Expires=1745193600&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=GsoKh7MpJqm2TJDByvMOwq8hI9WuXVJg5-9fmELiq~HpexPjVmAOwxZKvJbKG5vEx6dzq5p5tfeMXluTXtolvOhBUGIzaHS2agzOROw0EHNwLmPLLg26HLnT70TOK4g6Iejv-nn0cA5jfLZMsiXzecohVjpUTfcDG9PLSg4gaHF4PNu~VwxdSAb5OuZETkp8JIRzQUeNFin2AJQeNwYw~CSEDbCzMVsXfjESv4zKxXOXkJL5d35l4WzdBRkskLgzKenvCu8CxlKwMHv6xCTY3aZwbcKtk45qy8r7DubMr5CL4g3NOIDZEsWLugGfyParilJxJMx7WB-1e1zFvtVpUw__"
          }
        ]
      },
      {
        path: "variable",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "countDownInfo",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => ({
          joinWhiteList: { day: 0, hour: 0, minute: 0, second: 0 },
          whitelist: { day: 0, hour: 0, minute: 0, second: 0 }
        })
      },
      {
        path: "joinWhiteListTimerId",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 1
      },
      {
        path: "joinWhiteListTimerStart",
        type: "private",
        variableType: "dateString",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          "2025-06-08T02:11:02.442Z"
      },
      {
        path: "joinWhiteListTimerEnd",
        type: "private",
        variableType: "dateString",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          "2025-06-08T03:36:17.405Z"
      },
      {
        path: "isJoinWhitelist",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "isWhitelistFull",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "tabs.activeKey",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "1"
      },
      {
        path: "steps2.current",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0
      },
      {
        path: "whitelistTimerId",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0
      },
      {
        path: "whiteListImerEnd",
        type: "private",
        variableType: "dateString",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          "2025-06-08T03:42:41.640Z"
      },
      {
        path: "whitelistTimerStart",
        type: "private",
        variableType: "dateString",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          "2025-06-08T02:12:57.991Z"
      },
      {
        path: "hasMinted",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsiaU9BnxD99()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_css.plasmic_tokens,
            sty.root
          )}
          onLoad={async event => {
            const $steps = {};

            $steps["runCode"] = true
              ? (() => {
                  const actionArgs = {
                    customFunction: async () => {
                      return (() => {
                        function countdownTimer(startDate, endDate) {
                          const start = new Date(startDate);
                          const target = new Date(endDate);
                          const now = new Date();
                          if (now <= start || now > target) {
                            return {
                              days: 0,
                              hours: 0,
                              minutes: 0,
                              seconds: 0
                            };
                          }
                          const diff = target - now;
                          const days = Math.floor(diff / (1000 * 60 * 60 * 24));
                          const hours = Math.floor(
                            (diff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)
                          );
                          const minutes = Math.floor(
                            (diff % (1000 * 60 * 60)) / (1000 * 60)
                          );
                          const seconds = Math.floor(
                            (diff % (1000 * 60)) / 1000
                          );
                          return {
                            days,
                            hours,
                            minutes,
                            seconds
                          };
                        }
                        function startCountdown(
                          startDate,
                          endDate,
                          callback,
                          countType
                        ) {
                          const timer = setInterval(() => {
                            const timeLeft = countdownTimer(startDate, endDate);
                            callback(timeLeft);
                            if (
                              !timeLeft ||
                              (timeLeft.days === 0 &&
                                timeLeft.hours === 0 &&
                                timeLeft.minutes === 0 &&
                                timeLeft.seconds === 0)
                            ) {
                              clearInterval(timer);
                              if (countType === "JOIN_WHITELIST") {
                                $state.joinWhiteListTimerId = 0;
                              } else if (countType === "WHITELIST") {
                                $state.whitelistTimerId = 0;
                              }
                            }
                          }, 1000);
                          if (countType === "JOIN_WHITELIST") {
                            $state.joinWhiteListTimerId = timer;
                          } else if (countType === "WHITELIST") {
                            $state.whitelistTimerId = timer;
                          }
                        }
                        const whitelistStartTime =
                          Number(
                            $ctx.web3GlobalData.mintingInfo?.whitelistStartTime
                          ) * 1000 || $state.whitelistTimerStart;
                        const whitelistEndTime =
                          Number(
                            $ctx.web3GlobalData.mintingInfo?.whitelistEndTime
                          ) * 1000 || $state.whiteListImerEnd;
                        const joinWhitelistStartTime =
                          Number(
                            $ctx.web3GlobalData.mintingInfo?.presaleStartTime
                          ) * 1000 || $state.joinWhiteListTimerStart;
                        const joinWhitelistEndTime =
                          Number(
                            $ctx.web3GlobalData.mintingInfo?.presaleEndTime
                          ) * 1000 || $state.joinWhiteListTimerEnd;
                        let firstTime = true;
                        if (firstTime) {
                          $state.whitelistTimerId = 0;
                          $state.joinWhiteListTimerId = 0;
                          firstTime = false;
                        }
                        startCountdown(
                          joinWhitelistStartTime,
                          joinWhitelistEndTime,
                          timeLeft => {
                            console.log("joinWhitelistEndTime", timeLeft);
                            $state.countDownInfo.joinWhiteList.day =
                              timeLeft.days;
                            $state.countDownInfo.joinWhiteList.hour =
                              timeLeft.hours;
                            $state.countDownInfo.joinWhiteList.minute =
                              timeLeft.minutes;
                            $state.countDownInfo.joinWhiteList.second =
                              timeLeft.seconds;
                          },
                          "JOIN_WHITELIST"
                        );
                        startCountdown(
                          whitelistStartTime,
                          whitelistEndTime,
                          timeLeft => {
                            console.log(
                              "whitelistStartTime",
                              timeLeft,
                              whitelistStartTime,
                              whitelistEndTime
                            );
                            $state.countDownInfo.whitelist.day = timeLeft.days;
                            $state.countDownInfo.whitelist.hour =
                              timeLeft.hours;
                            $state.countDownInfo.whitelist.minute =
                              timeLeft.minutes;
                            $state.countDownInfo.whitelist.second =
                              timeLeft.seconds;
                          },
                          "WHITELIST"
                        );
                        const el = document.getElementById("root");
                        if (Boolean(el)) {
                          console.log("el", el);
                          return (el.style.width = "100%");
                        }
                      })();
                    }
                  };
                  return (({ customFunction }) => {
                    return customFunction();
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["runCode"] != null &&
              typeof $steps["runCode"] === "object" &&
              typeof $steps["runCode"].then === "function"
            ) {
              $steps["runCode"] = await $steps["runCode"];
            }
          }}
        >
          <div className={classNames(projectcss.all, sty.freeBox__gjgqk)}>
            <div className={classNames(projectcss.all, sty.freeBox__qS4Vp)}>
              <div className={classNames(projectcss.all, sty.freeBox__sitmU)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__rn0Di)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___101H8)}
                  >
                    <HomeSvgIcon
                      data-plasmic-name={"svg"}
                      data-plasmic-override={overrides.svg}
                      className={classNames(projectcss.all, sty.svg)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8RKw
                      )}
                    >
                      {"NFT Marketplace"}
                    </div>
                  </Stack__>
                  <ConnectWalletButton
                    className={classNames(
                      "__wab_instance",
                      sty.connectWalletButton__xEtXa
                    )}
                    connectText={"Connect Wallet"}
                    copyIcon={
                      <CopyIcon
                        className={
                          "" +
                          " " +
                          classNames("__wab_instance", sty.copyIcon__mJeQt)
                        }
                        iconColor={"#27273A"}
                      />
                    }
                    icon={
                      <WalletIcon
                        data-plasmic-name={"walletIcon"}
                        data-plasmic-override={overrides.walletIcon}
                        className={
                          "" +
                          " " +
                          classNames("__wab_instance", sty.walletIcon)
                        }
                      />
                    }
                    logoutIcon={
                      <LogoutIcon
                        className={
                          "" +
                          " " +
                          classNames(
                            "__wab_instance",
                            sty.logoutIconIcon___7QdJl
                          )
                        }
                      />
                    }
                    userIcon={
                      <UserIcon
                        className={
                          "" +
                          " " +
                          classNames("__wab_instance", sty.userIcon__w9NgR)
                        }
                      />
                    }
                  />
                </Stack__>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__uNHj3)}
                onClick={async event => {
                  const $steps = {};
                }}
              >
                <div className={classNames(projectcss.all, sty.freeBox__hdxX)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8Vfr
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return (
                            $ctx.web3GlobalData.mintingInfo?.name ||
                            "Magic Astronauts"
                          );
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return "Magic Astronauts";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__shuj3)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fhfGr)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__vpeba)}
                        displayHeight={"100%"}
                        displayMaxHeight={"400px"}
                        displayMaxWidth={
                          hasVariant(globalVariants, "screen", "tabletSmall")
                            ? "100%"
                            : "500px"
                        }
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tabletSmall")
                            ? "auto"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={(() => {
                          try {
                            return $ctx.web3GlobalData.mintingInfo?.status ===
                              "ACTIVE"
                              ? $ctx.web3GlobalData.mintingInfo?.imageUrl
                              : "https://suinova.var-meta.com/static/img/minting-illus.png";
                          } catch (e) {
                            if (e instanceof TypeError) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                        width={
                          hasVariant(globalVariants, "screen", "tabletSmall")
                            ? ``
                            : undefined
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fBp5)}
                    >
                      {(() => {
                        try {
                          return (
                            $state.joinWhiteListTimerId > 0 ||
                            !$state.isJoinWhitelist
                          );
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__b56Zo
                          )}
                        >
                          {"Join Whitelist"}
                        </div>
                      ) : null}
                      {(() => {
                        try {
                          return (
                            $state.joinWhiteListTimerId > 0 ||
                            !$state.isJoinWhitelist
                          );
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jW3I
                          )}
                        >
                          {"Exclusive minting for whitelisted members"}
                        </div>
                      ) : null}
                      {(() => {
                        try {
                          return (
                            !$state.isWhitelistFull && $state.isJoinWhitelist
                          );
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__tygEb
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__y5IA
                            )}
                          >
                            <AntdAvatar
                              className={classNames(
                                "__wab_instance",
                                sty.avatar___9AiOb
                              )}
                              letters={"AB"}
                              src={
                                "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAAGXcA1uAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAv0lEQVR4nO2UwQnDMAxFPUJHyAgGS5AxcmlrbZVRukFPsXLzCBklRa0DTTGpSpxT/SDg4K9vyUg2JgeMFJ8LZJpMKSD428r9YPA9eZd+MFdR0TJ/x4VrrxLKzeFWrrIplX4VVj6wsTvhcLZGKwamuWXf7BcD02zTpsq5Zd+ISPJVp7EEqcSVf8JK040UpT1geD3SxY2RaVL3nguXDtjfl7EoZrwgARIoBvJgruZvj/HWQZC+IsbZgwL1db7NUTwAP1uK7MUT0GgAAAAASUVORK5CYII="
                              }
                            />

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__kugrf
                              )}
                            >
                              {"You are on the whitelist!"}
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__ok9Sg
                            )}
                          >
                            <AntdAvatar
                              className={classNames(
                                "__wab_instance",
                                sty.avatar__mkIy8
                              )}
                              letters={"AB"}
                              src={
                                "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAAGXcA1uAAAACXBIWXMAAAsTAAALEwEAmpwYAAABWUlEQVR4nNVVy23DMAzVKBnBI/jShM2pI2STeJNkAxstJAG9KJu4m7B4llLoLzUtCpRAYEfm4/9RQjwgpHkkyRNpNvhjtkPJp0BD2Oeag69AwUR4KHkKzNQiMN77rqHtOSIP2ZaD4jmbQ2T+BBdPkoeuiDMxTYHys+KXjJdAiRRfRX8NRNoLgEjzuUv5b4Vm3iHh/WtaiDQHxbfobCy22a91UlIdgeIqZABjADhIXmqAlCixRUerYMBlxBPRkGAQSdcJRSWKFpTPxVmDpy8aa77EffmHQjYlQ4o/QDi3oZDe4tbY2rexUt4BnAzH8Z2H3B6BrsPUiX5vQvG7tBlU8KaY0VHy0BpAajjYdFDOOZNJF1j+QMeV59LRn9H/oS+Rg2Wf2dJ3AyZZDd8QetucNm4d6yS7vWuyUbiXma4UcLQiqqKejRg8ufXcRUVBnXH7eURDvx43+JvyCdxrTy98gsqgAAAAAElFTkSuQmCC"
                              }
                            />

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__z0BQu
                              )}
                            >
                              {
                                "Whitelist minting has not started yet. Check back soon!"
                              }
                            </div>
                          </div>
                        </div>
                      ) : null}
                      {(() => {
                        try {
                          return (
                            $state.isWhitelistFull && $state.isJoinWhitelist
                          );
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___2Aw3R
                          )}
                        >
                          <AntdAvatar
                            className={classNames(
                              "__wab_instance",
                              sty.avatar__nYGkN
                            )}
                            letters={"AB"}
                            src={
                              "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAlCAYAAAFQRQvsAAAACXBIWXMAAAsTAAALEwEAmpwYAAAC5ElEQVR4nL1X643DIAzOCDfCjeA/JzXQShmhI2SEbnAZoRskG/Q2SDfJCB3BJxMg4BhC2t4hIeUB9of9+UFV2YEK+io7UMPA3nFzB8YfGvjAAzSrv7IsjFdM/iOuBNPHI3RWyad5P8DnolVBiyc4u52oYQiesTI/7Q7U8OBq/LMTX8XqH6gswN0Da7iI5kcNE7fBgoNOpOAmSjQnCo/HThEtSDqb7zTzBGf3PgNq4CMhwQKlXQpa8af/QKfRVoWCuwjKLoTkT7PgNHs5OXN+chbGHISQYzRDA6xoo+DqTMaO0Xu6ubPXcKaXTqAXctgegYJrsM7wNmK3CF9Bi1+yIVHDyH3nNSOFkrWPeT5CI6LjNhSjNjFQQ28F9HnLazMp9G4OduBmMTT+ZmANZ+PSeXapoMiTTicZ26Y3h/ZQMPmsJwfWVE5lYVhDrwXtcS8N7y0XGh6mPSsSKsH/VD0Y5RfFUs5GgUj+OwXcrLzzx3ek8ouPcI3KSSI5e8E1XBz/f6onBjrEuUSEXwAO/rYQDvNgozaTFj0tjtDEOWHR8PALWEVN2ogbd2sEWW5BF4R6vykhR84g20/JzWH8MAqEggZm0NGkgqCRKIkvp/EupgGhjPzfQDV3V+9Ll5ol7Pwcs1mwWHFj6ldOMVWTO9YwUPxaX8ROjKPGl/E9hJ4EpbtPZ6kZyxJKQAldh73Ki2Wn6nCEXBWgft7di/uEurVwQa2zwMq8NtkVNZ50KBbwTN4obzywSuOarFj4NQmEek6+ngEnHdF/03uGvlPpDtgAItCFXY5Zm7Nc7IWeA+mrfxom5CMgdDULwrTaEjBfNb/FnEF8KMwXjLTd0niHH5/tJ3nuSd3gwtIXVi+B6W2SJ3MmTSY3o4TWJPixAsFlCfe9sXrz8H3vxoGdm3hKvr2S3MSaVZowUa43joxtTojJETOZ5f3PHgqlwrVnkvK/6IbQXWnpQkCkjOdlT9J7Pzjq2pvXiuQvXmZt0R21dFsAAAAASUVORK5CYII="
                            }
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gmgE7
                            )}
                          >
                            {
                              "Oops! Whitelist is full! No more spots available. \nLet\u2019s wait to public minting time"
                            }
                          </div>
                        </div>
                      ) : null}
                      {(() => {
                        try {
                          return (
                            $state.joinWhiteListTimerId > 0 ||
                            !$state.isJoinWhitelist
                          );
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kJvpx
                          )}
                        >
                          {"ENDS IN"}
                        </div>
                      ) : null}
                      {(() => {
                        try {
                          return (
                            $state.joinWhiteListTimerId > 0 ||
                            !$state.isJoinWhitelist
                          );
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <Stack__
                          as={"sub"}
                          data-plasmic-name={"sub"}
                          data-plasmic-override={overrides.sub}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.sub)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__ik1RJ
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__oDpp
                              )}
                            >
                              {""}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__uk0Lz
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return String(
                                      $state.countDownInfo.joinWhiteList.day ||
                                        0
                                    ).padStart(2, "0");
                                  } catch (e) {
                                    if (e instanceof TypeError) {
                                      return "01";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__hwl4Z
                              )}
                            >
                              {"day"}
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__s9DS
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___8GFjw
                              )}
                            >
                              {""}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__h21Rw
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return String(
                                      $state.countDownInfo.joinWhiteList.hour ||
                                        0
                                    ).padStart(2, "0");
                                  } catch (e) {
                                    if (e instanceof TypeError) {
                                      return "01";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__v7Jgw
                              )}
                            >
                              {"hour"}
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__iMeK
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__jrcRw
                              )}
                            >
                              {""}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___5Bk9
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return String(
                                      $state.countDownInfo.joinWhiteList
                                        .minute || 0
                                    ).padStart(2, "0");
                                  } catch (e) {
                                    if (e instanceof TypeError) {
                                      return "01";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__uvqn2
                              )}
                            >
                              {"minute"}
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__viJkg
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__e8HBo
                              )}
                            >
                              {""}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__gZ0XM
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return String(
                                      $state.countDownInfo.joinWhiteList
                                        .second || 0
                                    ).padStart(2, "0");
                                  } catch (e) {
                                    if (e instanceof TypeError) {
                                      return "01";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__qOne
                              )}
                            >
                              {"second"}
                            </div>
                          </div>
                        </Stack__>
                      ) : null}
                      {(() => {
                        try {
                          return (
                            ($state.joinWhiteListTimerId > 0 ||
                              !$state.isJoinWhitelist) &&
                            !$ctx.web3WalletData.walletAddress
                          );
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <ConnectWalletButton
                          className={classNames(
                            "__wab_instance",
                            sty.connectWalletButton__lNnnS
                          )}
                          connectText={"Connect Wallet"}
                          copyIcon={
                            <CopyIcon
                              className={
                                "" +
                                " " +
                                classNames(
                                  "__wab_instance",
                                  sty.copyIcon__zbUs9
                                )
                              }
                              iconColor={"#27273A"}
                            />
                          }
                          icon={null}
                          logoutIcon={
                            <LogoutIcon
                              className={
                                "" +
                                " " +
                                classNames(
                                  "__wab_instance",
                                  sty.logoutIconIcon__xthIo
                                )
                              }
                            />
                          }
                          userIcon={
                            <UserIcon
                              className={
                                "" +
                                " " +
                                classNames("__wab_instance", sty.userIcon__ddy4)
                              }
                            />
                          }
                        />
                      ) : null}
                      {(() => {
                        try {
                          return (
                            !!$ctx.web3WalletData.walletAddress &&
                            !$state.isJoinWhitelist
                          );
                        } catch (e) {
                          if (e instanceof TypeError) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <button
                          data-plasmic-name={"button"}
                          data-plasmic-override={overrides.button}
                          className={classNames(
                            projectcss.all,
                            projectcss.button,
                            projectcss.__wab_text,
                            sty.button
                          )}
                          onClick={async event => {
                            const $steps = {};

                            $steps["updateIsJoinWhitelist"] = true
                              ? (() => {
                                  const actionArgs = {
                                    variable: {
                                      objRoot: $state,
                                      variablePath: ["isJoinWhitelist"]
                                    },
                                    operation: 0,
                                    value: true
                                  };
                                  return (({
                                    variable,
                                    value,
                                    startIndex,
                                    deleteCount
                                  }) => {
                                    if (!variable) {
                                      return;
                                    }
                                    const { objRoot, variablePath } = variable;

                                    $stateSet(objRoot, variablePath, value);
                                    return value;
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["updateIsJoinWhitelist"] != null &&
                              typeof $steps["updateIsJoinWhitelist"] ===
                                "object" &&
                              typeof $steps["updateIsJoinWhitelist"].then ===
                                "function"
                            ) {
                              $steps["updateIsJoinWhitelist"] = await $steps[
                                "updateIsJoinWhitelist"
                              ];
                            }
                          }}
                        >
                          {"Join Whitelist"}
                        </button>
                      ) : null}
                    </div>
                  </Stack__>
                  <AntdTabs
                    data-plasmic-name={"tabs"}
                    data-plasmic-override={overrides.tabs}
                    activeKey={generateStateValueProp($state, [
                      "tabs",
                      "activeKey"
                    ])}
                    animateTabBar={true}
                    animateTabContent={false}
                    animated={true}
                    className={classNames("__wab_instance", sty.tabs)}
                    defaultActiveKey={"1"}
                    items={
                      <React.Fragment>
                        <AntdTabItem
                          className={classNames(
                            "__wab_instance",
                            sty.tabItem___7PDqC
                          )}
                          key={"1"}
                          label={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__thM8
                              )}
                            >
                              {"Overview"}
                            </div>
                          }
                        >
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__cgHi
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__sjO6F
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__iEc7V
                                )}
                              >
                                <React.Fragment>
                                  {(() => {
                                    try {
                                      return (
                                        $ctx.web3GlobalData.mintingInfo?.name ||
                                        "Magic Astronauts"
                                      );
                                    } catch (e) {
                                      if (e instanceof TypeError) {
                                        return "Magic Astronauts";
                                      }
                                      throw e;
                                    }
                                  })()}
                                </React.Fragment>
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__cU9Bn
                                )}
                              >
                                <React.Fragment>
                                  {(() => {
                                    try {
                                      return (
                                        $ctx.web3GlobalData.mintingInfo
                                          .description ||
                                        `Embark on a Cosmic Journey with Magic Astronauts! 🚀✨
Welcome to the Magic Astronauts NFT collection—a mesmerizing fusion of space exploration and ethereal wonder! Each Magic Astronaut is a unique digital masterpiece, blending futuristic space gear with mystical elements that capture the boundless imagination of the cosmos.
`
                                      );
                                    } catch (e) {
                                      if (e instanceof TypeError) {
                                        return "Embark on a Cosmic Journey with Magic Astronauts! \ud83d\ude80\u2728\nWelcome to the Magic Astronauts NFT collection\u2014a mesmerizing fusion of space exploration and ethereal wonder! Each Magic Astronaut is a unique digital masterpiece, blending futuristic space gear with mystical elements that capture the boundless imagination of the cosmos.";
                                      }
                                      throw e;
                                    }
                                  })()}
                                </React.Fragment>
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__shZq5
                                )}
                              >
                                {"Collection Highlights"}
                              </div>
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__wOdjT
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    sty.li___9HtLz
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__joT4M
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__onQLa
                                      )}
                                    >
                                      {
                                        "Unique Artworks: 1,000 one-of-a-kind NFTs, each featuring a Magic Astronaut with distinct traits, suits, and cosmic backgrounds."
                                      }
                                    </div>
                                  </div>
                                </li>
                              </ul>
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__dEKrg
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    sty.li___5H2Xj
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__rfaSk
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__yn765
                                      )}
                                    >
                                      {
                                        "Surreal Aesthetics: Inspired by the intersection of science fiction and fantasy, our astronauts float through enchanted cloudscapes, glowing nebulae, and starry voids."
                                      }
                                    </div>
                                  </div>
                                </li>
                              </ul>
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__s8D
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    sty.li__mbBha
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox___6XVqh
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__z1SzG
                                      )}
                                    >
                                      {
                                        "Utility & Perks: Holders gain access to exclusive virtual space expeditions, community events, and future airdrops in the Magic Astronauts universe."
                                      }
                                    </div>
                                  </div>
                                </li>
                              </ul>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__dWjMb
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__e0Ct7
                                )}
                              >
                                {"Vision"}
                              </div>
                              <AntdSteps
                                data-plasmic-name={"steps2"}
                                data-plasmic-override={overrides.steps2}
                                className={classNames(
                                  "__wab_instance",
                                  sty.steps2
                                )}
                                current={generateStateValueProp($state, [
                                  "steps2",
                                  "current"
                                ])}
                                direction={"vertical"}
                                items={(() => {
                                  const __composite = [
                                    { title: null, description: null },
                                    { title: null, description: null },
                                    { title: null, description: null }
                                  ];
                                  __composite["0"]["title"] = new Date(
                                    $ctx.web3GlobalData.mintingInfo?.visions[0]?.visionTime
                                  )?.toDateString();
                                  __composite["0"]["description"] =
                                    $ctx.web3GlobalData.mintingInfo.visions[0]
                                      .description ||
                                    "Early access and exclusive benefits for early supporters";
                                  __composite["1"]["title"] = new Date(
                                    $ctx.web3GlobalData.mintingInfo?.visions[1]?.visionTime
                                  )?.toDateString();
                                  __composite["1"]["description"] =
                                    $ctx.web3GlobalData.mintingInfo.visions[1]
                                      .description ||
                                    "Priority minting for whitelisted members";
                                  __composite["2"]["title"] = new Date(
                                    $ctx.web3GlobalData.mintingInfo?.visions[2]
                                      ?.visionTime
                                      ? $ctx.web3GlobalData.mintingInfo
                                          ?.visions[2]?.visionTime
                                      : new Date(
                                          $ctx.web3GlobalData.mintingInfo?.visions[1]?.visionTime
                                        ).setDate(
                                          new Date(
                                            $ctx.web3GlobalData.mintingInfo?.visions[1]?.visionTime
                                          ).getDate() + 3
                                        )
                                  )?.toDateString();
                                  __composite["2"]["description"] =
                                    $ctx.web3GlobalData.mintingInfo?.visions[2]
                                      ?.description || "Milestone 3";
                                  return __composite;
                                })()}
                                onChange={async (...eventArgs: any) => {
                                  generateStateOnChangeProp($state, [
                                    "steps2",
                                    "current"
                                  ]).apply(null, eventArgs);
                                }}
                                progressDot={false}
                                responsive={true}
                                size={"small"}
                                status={"finish"}
                                type={"default"}
                              />
                            </div>
                          </Stack__>
                        </AntdTabItem>
                        <AntdTabItem
                          className={classNames(
                            "__wab_instance",
                            sty.tabItem___4HTks
                          )}
                          key={"2"}
                          label={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__vy1Zs
                              )}
                            >
                              {"Team"}
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__vjAhj
                            )}
                          >
                            {(_par =>
                              !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                              (() => {
                                try {
                                  return $ctx.web3GlobalData.mintingInfo.teams;
                                } catch (e) {
                                  if (e instanceof TypeError) {
                                    return [];
                                  }
                                  throw e;
                                }
                              })()
                            ).map((__plasmic_item_0, __plasmic_idx_0) => {
                              const currentItem = __plasmic_item_0;
                              const currentIndex = __plasmic_idx_0;
                              return (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__uBFpd
                                  )}
                                  key={currentIndex}
                                >
                                  <PlasmicImg__
                                    alt={""}
                                    className={classNames(sty.img___7EjO)}
                                    displayHeight={
                                      hasVariant(
                                        globalVariants,
                                        "screen",
                                        "mobileSmall"
                                      )
                                        ? "350px"
                                        : hasVariant(
                                            globalVariants,
                                            "screen",
                                            "mobileLarge"
                                          )
                                        ? "280px"
                                        : hasVariant(
                                            globalVariants,
                                            "screen",
                                            "tabletSmall"
                                          )
                                        ? "260px"
                                        : "160px"
                                    }
                                    displayMaxHeight={
                                      hasVariant(
                                        globalVariants,
                                        "screen",
                                        "tabletSmall"
                                      )
                                        ? "none"
                                        : "160px"
                                    }
                                    displayMaxWidth={"100%"}
                                    displayMinHeight={"0"}
                                    displayMinWidth={"0"}
                                    displayWidth={"auto"}
                                    loading={"lazy"}
                                    src={
                                      "https://dev-suinova.s3.ap-southeast-1.amazonaws.com/e2ace5c90508b6d2ef3467112d232da0.jpg"
                                    }
                                  />

                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__xjpY
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__eHCxe
                                      )}
                                    >
                                      <React.Fragment>
                                        {(() => {
                                          try {
                                            return currentItem.memberName;
                                          } catch (e) {
                                            if (e instanceof TypeError) {
                                              return "James";
                                            }
                                            throw e;
                                          }
                                        })()}
                                      </React.Fragment>
                                    </div>
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__dtBen
                                      )}
                                    >
                                      <React.Fragment>
                                        {(() => {
                                          try {
                                            return currentItem.memberTitle;
                                          } catch (e) {
                                            if (e instanceof TypeError) {
                                              return "Co Founder";
                                            }
                                            throw e;
                                          }
                                        })()}
                                      </React.Fragment>
                                    </div>
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                        </AntdTabItem>
                      </React.Fragment>
                    }
                    onChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "tabs",
                        "activeKey"
                      ]).apply(null, eventArgs);
                    }}
                    sticky={false}
                    tabBarBackground={"#FFF"}
                    tabsDropdownScopeClassName={sty["tabs__tabsDropdown"]}
                    tabsScopeClassName={sty["tabs__tabs"]}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg", "walletIcon", "sub", "button", "tabs", "steps2"],
  svg: ["svg"],
  walletIcon: ["walletIcon"],
  sub: ["sub"],
  button: ["button"],
  tabs: ["tabs", "steps2"],
  steps2: ["steps2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
  walletIcon: typeof WalletIcon;
  sub: "sub";
  button: "button";
  tabs: typeof AntdTabs;
  steps2: typeof AntdSteps;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicConnectWalletViewMintingNftDetails__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicConnectWalletViewMintingNftDetails__VariantsArgs;
    args?: PlasmicConnectWalletViewMintingNftDetails__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit< // Specify variants directly as props
    PlasmicConnectWalletViewMintingNftDetails__VariantsArgs,
    ReservedPropsType
  > &
    // Specify args directly as props
    Omit<
      PlasmicConnectWalletViewMintingNftDetails__ArgsType,
      ReservedPropsType
    > &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames:
            PlasmicConnectWalletViewMintingNftDetails__ArgProps,
          internalVariantPropNames:
            PlasmicConnectWalletViewMintingNftDetails__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicConnectWalletViewMintingNftDetails__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicConnectWalletViewMintingNftDetails";
  } else {
    func.displayName = `PlasmicConnectWalletViewMintingNftDetails.${nodeName}`;
  }
  return func;
}

export const PlasmicConnectWalletViewMintingNftDetails = Object.assign(
  // Top-level PlasmicConnectWalletViewMintingNftDetails renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    walletIcon: makeNodeComponent("walletIcon"),
    sub: makeNodeComponent("sub"),
    button: makeNodeComponent("button"),
    tabs: makeNodeComponent("tabs"),
    steps2: makeNodeComponent("steps2"),

    // Metadata about props expected for PlasmicConnectWalletViewMintingNftDetails
    internalVariantProps:
      PlasmicConnectWalletViewMintingNftDetails__VariantProps,
    internalArgProps: PlasmicConnectWalletViewMintingNftDetails__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicConnectWalletViewMintingNftDetails;
/* prettier-ignore-end */
